FROM python:3.11
ADD . /code
WORKDIR /code
RUN apt-get update -y && \
    apt-get install -y libldap2-dev libsasl2-dev libpq-dev lcov valgrind
RUN pip install --upgrade pip && \
    pip install -r requirements.txt
CMD python main.py